### ISSUE TITLE
add Alice in Wonderland

### ISSUE THREAD

**Issue by lagleki** [mhagiwara/zmifanva#1]
https://docs.google.com/spreadsheets/d/1_vkiwqOIOIJPqZTiomzd4ApUSEQXhEY6CeyZD_6c-PA/edit#gid=0

columns A and B are mostly aligned except cells marked in red (they cannot be aligned so they can just be removed for now).

for other columns they are either not ready to be used or not aligned for now.

**Comment by mhagiwara** [comment]
Thanks, this looks awesome! Should I use the original xorxes translation or the new ones by gleki?

**Comment by lagleki** [comment]
no, gleki's Alice is not ready yet. Use xorxe's.

Em sábado, 26 de dezembro de 2015, Masato Hagiwara notifications@github.com
escreveu:

**Comment by lagleki** [comment]
Oh actually there are some parts that dont allow for literal and perfect translation. Like the poem in the beginning. Such poems can be deleted from the corpus (although Google Translate seems to be retaining such things) as well as untranslatable play on words.

**Comment by mhagiwara** [comment]
Looks like we need some cleaning here. For example, there are too many long sentences that are not necessarily suited as training sentences (could there be a way to extract shorter sentences?). Actually, the preprocessing script I use discards any sentence pairs longer than 80 words. Also, there seem to be too many utterance sentences (lu ... li'u) with 'sei' embedded, and I'm afraid we might do some structure normalization (e.g., removing lu ... sei do'e cusku li'u AND " ... " said someone from both of the sentences)

**Comment by lagleki** [comment]
i wont work now on that given that the actual updated translation is necessary. others can try Hunalign  or similar things for now.

**Comment by mhagiwara** [comment]
Closing this for now.
