### ISSUE TITLE
Simpler Reporting Mechanism

### ISSUE THREAD

**Issue by selrun** [mhagiwara/zmifanva#2]
The current reporting mechanism is not very user friendly. When the _report_ button is pressed, the current contents of the input and output textboxes should be automatically made part of the report. If this is possible via Google Docs, then the fix will be simple, however if it is not, then I assume you will have to build a reporting feature.

**Comment by lagleki** [comment]
technically we can make something like Tatoeba but with stricter moderating.
A simple spreadsheet with sentences and their translations. Both columns can be improved.

**Comment by selrun** [comment]
This functions based on machine learning  sentences like this, so this could work well.
