### ISSUE TITLE
Moses or sequence-to-sequence model

### ISSUE THREAD

**Issue by sorpaas** [mhagiwara/zmifanva#3]
I find in this repository that there's a `seq2seq` model code, but it seems that `scripts` for preprocessing and training are using moses. Is the sequence-to-sequence model working?

**Comment by mhagiwara** [comment]
I also tried the `seq2seq` model but the translation quality (measured in BLEU) was not as good as Moses. So the current implementation (what you can see on http://lojban.lilyx.net/zmifanva/) still uses Moses.
