### ISSUE TITLE
Display backtranslation

### ISSUE THREAD

**Issue by JRHaigh** [mhagiwara/zmifanva#4]
Please have 3 boxes: input; output; and backtranslation. Backtranslation is a very useful indicator of translation quality, and helps to highlight the ambiguities. E.g.:
English | glibau:
> My name is J. R. Haigh.

Lojban | lojban:
> lo cmene be mi cu J. R. Haigh lo

English backtranslation | lo glibau fanva xruti:
> My name is J Haigh that.
----
English | glibau:
> My name is JRHaigh.

Lojban | lojban:
> lo cmene be mi cu JRHaigh lo

English backtranslation | lo glibau fanva xruti:
> My name is JRHaigh.
----
English | glibau:
> If you are looking to search human translated, high quality Lojban-English bilingual sentences, try zmifanva's sister project jufsisku.

Lojban | lojban:
> do jaginai catlu lo nu sisku tu'a lo remna pu fanva je galtu quality Lojban-English bilingual jufra gi'e troci lo nu zmifanva cu mensi project jufsisku lo

English backtranslation | lo glibau fanva xruti:
> If you are looking for searching for a human translated and high quality Lojban-English bilingual sentence and trying to zmifanva is sister jufsisku project.

**Comment by JRHaigh** [comment]
However, seeing as Lojban is apparently unambiguous, backtranslation shouldn't be needed when translating _to_ it. Perfect translation to any unambiguous language should surely have a backtranslation identical to the original. Furthermore, translation from an ambiguous language to an unambiguous language should have multiple possible answers, all of which have a backtranslation identical to the original. It's a one-to-many relationship, I think.
&nbsp;&nbsp;&nbsp;&nbsp;Imagine this ideal translator:
Ambiguous language:
> \<input>

Unambiguous language:
> <output 1>
> or
> <output 2>
> or
> <output 3>
> etc.

(Backtranslation unneeded because they should all backtranslate to the original.)

----
Unambiguous language:
> \<input>

Ambiguous language:
> \<output>

Unambiguous language backtranslation:
> <backtranslation 1>
> or
> <backtranslation 2>
> or
> <backtranslation 3>
> etc.

**Comment by JRHaigh** [comment]
Hmm, then again, if a language is not only ambiguous but has multiple ways to express exactly the same meaning then its translation relation with any other language is many-to-many, even if the other language is perfectly-unambiguous.
&nbsp;&nbsp;&nbsp;&nbsp;Nonetheless, there can still be a ‘preferred form’ for a particular meaning – probably the one that's least ambiguous.

**Comment by JRHaigh** [comment]
I suppose that an ideal translator could be better at finding the preferred form than the human. If each output has a backtranslation that seeks to distinguish the various outputs, i.e., interpretations, with minimal ambiguity then the backtranslation of the intended interpretation may be preferable to the input.
&nbsp;&nbsp;&nbsp;&nbsp;With this in-mind, a better layout would be to provide a list of bilingual answers, formed of the backtranslation and translation, like so:
English or Lojban input | lo glico je la lojban:
> \<original>

[Translate from English | ???] [Translate from Lojban | ???]

Bilingual English and Lojban output | relbau lo glico je la lojban:
> <interpretation 1 in English> | <interpretation 1 in Lojban>

> <interpretation 2 in English> | <interpretation 2 in Lojban>

> <interpretation 3 in English> | <interpretation 3 in Lojban>

(etc.)

**Comment by JRHaigh** [comment]
If you can get the software to interpret input that's a mixture of the 2 languages then there wouldn't need to be 2 translate buttons:
English or Lojban input | lo glico je la lojban:
> \<original>

[Translate]

Bilingual English and Lojban output | relbau lo glico je la lojban:
> <interpretation 1 in English> | <interpretation 1 in Lojban>

> <interpretation 2 in English> | <interpretation 2 in Lojban>

> <interpretation 3 in English> | <interpretation 3 in Lojban>

(etc.)

**Comment by mhagiwara** [comment]
You can always check back translation yourself. I'm not implementing it.
